### ISSUE TITLE
Parsing inconsistency: lazy paragraph lines in lists

### ISSUE THREAD

**Issue by rauschma** [jgm/djot#290]
I found the following parsing inconsistency. It’s obvious why it happens but it feels like an argument in favor of requiring indentation – because without it you once again have to be careful about not starting paragraph lines with special characters (thematic breaks, list item bullets, etc.).

## Inside a list

Input:

```md
* abc
- - -
```

Output (the three hyphens become an `<hr>` after the list and not regular text inside the list item’s paragraph):

```html
<ul>
<li>
abc
</li>
</ul>
<hr>
```

## Normal paragraph

Input:

```md
abc
- - -
```

Output:

```html
<p>abc
- - -</p>
```

**Comment by jgm** [comment]
I wouldn't call it an inconsistency; it's just that the behavior of lazy lines isn't fully described in the (rather sketchy) documentation.

The basic rule the parser uses is this:  If a line would not start any other kind of block (besides a paragraph), and the last open container is a paragraph, then it gets added to that paragraph.

Since this line would be a thematic break, it doesn't qualify as a lazy paragraph continuation.

Certainly it's a good practice not to use laziness if you want to avoid this sort of thing.  But I don't think that's an argument for banishing laziness.

**Comment by rauschma** [comment]
Ah, I understand: For lazy lines, you have to be more careful w.r.t. how you start your lines.

**Comment by rauschma** [comment]
> The basic rule the parser uses is this: If a line would not start any other kind of block (besides a paragraph), and the last open container is a paragraph, then it gets added to that paragraph.

As an aside: It’s interesting that this rule applies at any level of nesting (via indentation or quoting) – each of the following pairs of lines produces the same output.

```md
> > > abc
> > > def

> > > abc
> > def

> > > abc
> def

> > > abc
def
```

**Comment by vassudanagunta** [comment]
Yes, that behavior is very counterintuitive:


```
>> This is inside the nested block quote.
>And so is this.
>And this.
>
>But not this.
```

renders [like this](https://babelmark.github.io/?text=%0A%3E%3E+This+is+inside+the+nested+block+quote.%0A%3EAnd+so+is+this.%0A%3EAnd+this.%0A%3E%0A%3EBut+not+this.%0A%0A).

But that link also shows the dominance of that interpretation, so it can't really be changed. Gruber's original Markdown also does the same.
