### ISSUE TITLE
Proposal: allow bare references

### ISSUE THREAD

**Issue by KAAtheWiseGit** [jgm/djot#322]
Currently, bare reference (`[ref]` as a shortcut to `[ref][ref]`) are forbidden to ensure parsing locality.  I think its possible to allow the prior without sacrificing the latter.

I'd suggest allowing bare references, as long as they are not immediately followed by another reference.  That is, `[foo] [bar]` gets treated as `[foo][foo] [bar][bar]`, but `[foo][bar]` is interpreted as the work `foo` with a reference to `bar`.

The Lua parser keeps a stack of parenthesis, so it's possible to add an [else clause on the `]` matcher][code], if it doesn't find an opening `[`, `{`, or `(`.  Unsure about the other parsers, though.

I think that it'll make bare references easier to read and write and increase compatibility with existing Markdown documents.  A parser with such logic will misparse `[foo][bar]` from Markdown, but current rules already do that.

[code]: https://github.com/jgm/djot.lua/blob/main/djot/inline.lua#L329

**Comment by jgm** [comment]
Compatibility with existing markdown documents isn't really a design goal.  If you need to convert a markdown document to djot, you can use pandoc.

If we allowed bare references but kept parsing locality, it would mean parsing *every bracketed text* as a reference.  That is probably not desired, because brackets are used in ordinary text.

So I'm not in favor of this proposal.

**Comment by bpj** [comment]
In my experience if your text contains "plain" brackets as well shortcut link references create more trouble than they solve: sooner or later you *will* have a conflict, and probably overlook it.

**Comment by KAAtheWiseGit** [comment]
My main motivation was that I found typing the closing brackets awkward.  But I didn't think about the non-reference brackets usage.  It would indeed become a problem
